// frontend/src/config/roles.js
// Single source of truth for roles & page permissions

/* ================= Roles ================= */

export const ROLES = {
  SUPERVISOR: "Supervisor",
  MECHANIC: "Mechanic",
  DRIVER: "Driver",
  CLEANER: "Cleaning Guy",
  ADMIN: "Admin",           // 🆕 NEW: Full access (including Users page)
  GUEST: "Guest",           // 🆕 NEW: Access to all except Users page
  MANAGER: "Manager",       // 🆕 NEW: Read-only access to history pages
};

/* ================= Page Permissions ================= */

export const PAGE_PERMISSIONS = {
  // Checklist
  CHECKLIST: [ROLES.SUPERVISOR, ROLES.DRIVER, ROLES.ADMIN, ROLES.GUEST],
  CHECKLIST_FORM: [ROLES.SUPERVISOR, ROLES.DRIVER, ROLES.ADMIN, ROLES.GUEST],
  CHECKLIST_HISTORY: [ROLES.SUPERVISOR, ROLES.DRIVER, ROLES.ADMIN, ROLES.GUEST, ROLES.MANAGER],  // ✅ Manager can view

  // Maintenance
  MAINTENANCE: [ROLES.SUPERVISOR, ROLES.MECHANIC, ROLES.DRIVER, ROLES.ADMIN, ROLES.GUEST],
  MAINTENANCE_FORM: [ROLES.SUPERVISOR, ROLES.MECHANIC, ROLES.ADMIN, ROLES.GUEST],
  MAINTENANCE_HISTORY: [ROLES.SUPERVISOR, ROLES.MECHANIC, ROLES.DRIVER, ROLES.ADMIN, ROLES.GUEST, ROLES.MANAGER],  // ✅ Manager can view

  // Cleaning
  CLEANING: [ROLES.SUPERVISOR, ROLES.MECHANIC, ROLES.DRIVER, ROLES.CLEANER, ROLES.ADMIN, ROLES.GUEST],
  CLEANING_FORM: [ROLES.SUPERVISOR, ROLES.MECHANIC, ROLES.CLEANER, ROLES.ADMIN, ROLES.GUEST],
  CLEANING_HISTORY: [ROLES.SUPERVISOR, ROLES.MECHANIC, ROLES.DRIVER, ROLES.CLEANER, ROLES.ADMIN, ROLES.GUEST, ROLES.MANAGER],  // ✅ Manager can view

  // Equipment
  EQUIPMENT: [ROLES.SUPERVISOR, ROLES.MECHANIC, ROLES.DRIVER, ROLES.ADMIN, ROLES.GUEST],
  EQUIPMENT_LIST: [ROLES.SUPERVISOR, ROLES.MECHANIC, ROLES.DRIVER, ROLES.ADMIN, ROLES.GUEST, ROLES.MANAGER],  // ✅ Manager can view
  EQUIPMENT_MANAGE: [ROLES.SUPERVISOR, ROLES.ADMIN, ROLES.GUEST],

  // Users
  USERS: [ROLES.ADMIN],  // 🔒 Only Admin (Supervisor removed)
};
